%------------------------------
% Load cdf file into bats class
if 0
  s = '/home/spiegel/Desktop/Programs/SWMF/data/3d__var_1_e20150321-122300-000.out.cdf';
  % to load all variables
  original = bats('file',s);
  % remove the variables we will not use
  original.clearFields({'b1x','b1y','b1z','e'})
  % Convert to uniform grid (batsUni class)
  uni = original.toBatsUni(0.125,{},'xrange',[-40 0],'yrange',[-15 15],'zrange',[-15 15]);
  % save('/home/spiegel/Desktop/Programs/SWMF/data/uni.mat','uni','-v7.3');
else
  load('/home/spiegel/Desktop/Programs/SWMF/data/uni.mat');
end

uni.plot('newfigure',...
          'slice',...
          'xslice',-40,...
          'variable','p',...
          'log',...
          'colorrange',[2e-2 1e-1],...
          'colorposition','westoutside',...
          'color','jet',...
          'alpha',0.7);

uni.plot('isosurface',...
          'variable','bx',...
          'level',0,...
          'colorvariable','bz',...
          'colorrange',[-2 14],...
          'color','parula',...
          'colorposition','eastoutside',...
          'xrange',[-40 -1],'zrange',[-3 3],...
          'alpha',0.7);

uni.plot('slice',...
          'yslice',0,...
          'variable','ux',...
          'colorrange',[-300 300],...
          'colorposition','northoutside',...
          'color','copper',...
          'alpha',0.7);

uni.plot('stream',...
          'variable','b',...
          'start',[-10.38 -2.75 0; -5.38 -2.75 0; -30.38 -2.75 0],...
          'LineWidth',2);

uni.plotEarth;
