%------------------------------
% Load cdf file into bats class
if 0
  s = 'path/to/CDF.cdf';
  %s = '/home/spiegel/Desktop/Programs/SWMF/data/3d__var_1_e20150321-122300-000.out.cdf';
  % to load all variables
  original = bats('file',s);
  % remove the variables we will not use
  original.clearFields({'b1x','b1y','b1z','e'});
  % Convert to uniform grid (batsUni class)
  uni = original.toBatsUni(0.125,{},'xrange',[-25  20],'yrange',[-20 20],'zrange',[-20 20]);
  % save('/home/spiegel/Desktop/Programs/SWMF/data/uni_interp.mat','uni','-v7.3');

else
  load('Path/to/data/converted/to/batsUni/format');
end

% uni is the name of the object of the class batsUni
uni.plot('newfigure',...
          'slice',...
          'xslice',-40,...
          'variable','p',...
          'log',...
          'colorrange',[2e-2 1e-1],...
          'colorposition','westoutside',...
          'color','jet',...
          'alpha',0.7);

uni.plot('quiver',...
          'variable','u', ...
          'xrange',[-20 -15], ...
          'yrange',[-5 5], ...
          'zrange',1,...
          'increment',2,...
          'color','cool',...
          'colorrange',[0 800],...
          'length','equal',...
          'MagUnitLength',0.25,...
          'HeadAngle',90,...
          'HeadLength',0.125/3);

uni.plot('isosurface',...
          'variable','bx',...
          'level',0,...
          'colorvariable','bz',...
          'colorrange',[-2 14],...
          'color','parula',...
          'colorposition','eastoutside',...
          'xrange',[-40 -1],'zrange',[-3 3],...
          'alpha',0.7);

uni.plot('slice',...
          'yslice',0,...
          'variable','ux',...
          'colorrange',[-300 300],...
          'colorposition','northoutside',...
          'color','copper',...
          'alpha',0.7);

uni.plot('stream',...
          'variable','b',...
          'start',[-10.38 -2.75 0; -5.38 -2.75 0; -30.38 -2.75 0],...
          'LineWidth',2);

uni.plotEarth;
